Learning Numpy

In [1]:
import numpy as np

Creating the Numpy using lists

In [3]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(arr_2d)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### lists vs numpy 

In [6]:
list_py = [1, 2, 3, 4, 5]
print("Multplication in lists:",list_py * 2)  # This will concatenate the list

array_py = np.array([1, 2, 3, 4, 5])
print("Multiplication in Numpy array:",array_py * 2)  # This will perform element-wise multiplication

Multplication in lists: [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
Multiplication in Numpy array: [ 2  4  6  8 10]


### Arrays from Scratch

In [7]:
ones = np.ones((3, 4))
print("Array of ones:\n", ones)

zeros = np.zeros((2, 5))
print("Array of zeros:\n", zeros)   

full = np.full((2, 3), 7)
print("Array filled with 7s:\n", full)

Array of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Array of zeros:
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
Array filled with 7s:
 [[7 7 7]
 [7 7 7]]


In [ ]:

random = np.random.rand(2, 3)*10+1
print("Array with random values:\n", random)

sequence = np.arange(0, 21, 2)
print("Array with a sequence of numbers:\n", sequence)

Array with random values:
 [[ 6.99509464  4.41937897 10.17873659]
 [ 4.11584108  8.49233421  3.12229181]]
Array with a sequence of numbers:
 [ 0  2  4  6  8 10 12 14 16 18 20]


### Vector , Matrices , Tensor

In [17]:
vector = np.array([1, 2, 3])
print("Vector:\n", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:\n", matrix)  

tensor = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("Tensor:\n", tensor)

Vector:
 [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [18]:
array = np.array([[1, 2, 3], [4, 5, 6]])
print("Array shape:", array.shape)  
print("Array data type:", array.dtype)
print("Array number of dimensions:", array.ndim)
print("Array size (number of elements):", array.size)


Array shape: (2, 3)
Array data type: int64
Array number of dimensions: 2
Array size (number of elements): 6


### Array Reshaping

In [19]:
array = np.arange(12)
reshaped_array = array.reshape((3, 4))
print("Reshaped Array (3x4):\n", reshaped_array)
flattened_array = reshaped_array.flatten()
print("Flattened Array:\n", flattened_array)
raveled_array = reshaped_array.ravel()
print("Raveled Array:\n", raveled_array) # gives a flattened view without making a copy
transposed_array = reshaped_array.T
print("Transposed Array:\n", transposed_array)

Reshaped Array (3x4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled Array:
 [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed Array:
 [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
