In [1]:
import numpy as np
import matplotlib.pyplot as plt


Matplotlib is building the font cache; this may take a moment.


In [3]:
# data = [restuarantid, 2022,2023,2024,2025]

sales_data = np.array([
    [1, 1500, 1600, 1700, 1800],
    [2, 2000, 2100, 2200, 2300],
    [3, 2500, 2600, 2700, 2800],
    [4, 3000, 3100, 3200, 3300],
])

# extract data of first 3 restaurants
first_three_restaurants = sales_data[:3, :]
print("First three restaurants' data:\n", first_three_restaurants)  

First three restaurants' data:
 [[   1 1500 1600 1700 1800]
 [   2 2000 2100 2200 2300]
 [   3 2500 2600 2700 2800]]


In [4]:
# total sales for each year
total_sales_per_year = np.sum(sales_data[:, 1:], axis=0)
print("Total sales per year:", total_sales_per_year)   


Total sales per year: [ 9000  9400  9800 10200]
